---
curso: "Introducción a la minería de datos"
title: "Ejercicio en Clase"
author: Jessica Elizabeth Botón Pérez
carne: 999014960
---

install.packages("arules")
library(arules)



```{r}
data <- read.csv('C:\\Users\\Pc\\Downloads\\db_csv_\\HOGAR_BDP.csv', sep=",")

data
```



```{r}
# Definimos los parametros del algoritmo Apriori

reglas <- apriori(data, parameter = list(support=0.2, confidence=0.5))
 
#Ahora inspeccionamos las reglas

inspect(reglas[0:100])
inspect(reglas[100:200])
inspect(reglas[200:300])
```



```{r}
# Filtramos por departamento Guatemala para continuar analizando

data2 <- subset(data, DEPARTAMENTO == 1)

# Eliminamos la columna que contiene todos los datos iguales (depto = 1) para mantener un buen nivel de entropía y evitar error al ejecutar

data2 <- data2[,-1]


reglas2 <- apriori(data2, parameter = list(support=0.2, confidence=0.5))

inspect(reglas2[0:100])
inspect(reglas2[100:200])
inspect(reglas2[200:300])
```



```{r}
data3 <- subset(data2, MUNICIPIO == 101)
data3 <- data3[,-1]
data3 <- data3[,-1]
data3 <- data3[,-39]
data3 <- data3[,-38]
data3 <- data3[,-6]
data3 <- data3[,-23]
reglas3 <- apriori(data3, parameter = list(support=0.2, confidence=0.5))

inspect(reglas3[0:100])
inspect(reglas3[100:200])
inspect(reglas3[500:600])
inspect(reglas3[600:700])
```



```{r}
# Al modificar el soporte y la confianza podemos ver como la cantidad de reglas disminuyen

reglas3 <- apriori(data3, parameter = list(support=0.3, confidence=0.6))
```








