---
curso: "Introducción a la minería de datos"
title: "Ejercicio en Clase"
author: Jessica Elizabeth Botón Pérez
carne: 999014960
---

install.packages("ggplot2")
library(ggplot2)


```{r}

data = read.csv('C:/Users/Dgo/Downloads/AJess/db_csv_/MIGRACION_BDP.csv', sep=',')

data

```

```{r}

#Ejecutamos el comando para utilizar la clusterización por Kmeans con 4 centroides
cluster <- kmeans(data, centers=4)

cluster

```



```{r}

# Utilizaré la regla # 3 del ejercicio anterior donde por medio de FpGrowth encontré una correlación entre los años en que las personas migraron y los departamentos de donde predominaron.

#Defino los parametros para gráficar

grafica <- ggplot(data, aes(x = DEPARTAMENTO, y = PEI5, color = as.factor(cluster$cluster)))+
  geom_point()+
  geom_point(data = as.data.frame(cluster$centers), aes(x=DEPARTAMENTO, y = PEI5), color = "black", size=4, shape=17)+
  labs(title = "Deparamento vs Año Emigración")+
  theme_minimal()

grafica


```



```{r}

# Al ver la gráfica nos percatamos que registros con año 9999 distorsionan el resultado

#Filtramos por omitiendo los años de 9999

dataf <- subset(data, PEI5 > 2012 & PEI5 < 2025)

dataf

# Ejecutamos Kmeans con el nuevo dataset
clusterf <- kmeans(dataf, centers=3)

clusterf

```


```{r}

#Defino los parametros para gráficar

graficaf <- ggplot(dataf, aes(x = DEPARTAMENTO, y = PEI5, color = as.factor(clusterf$cluster)))+
  geom_point()+
  geom_point(data = as.data.frame(clusterf$centers), aes(x=DEPARTAMENTO, y = PEI5), color = "black", size=4, shape=17)+
  labs(title = "Deparamento vs Año Emigración")+
  theme_minimal()


graficaf


```


```{r}

# Ejecutamos Kmeans con el nuevo dataset
clusterf2 <- kmeans(data, centers=4)

clusterf2

#Grafica
graficaf2 <- ggplot(dataf, aes(x = PEI4, y = ID_EMIGRACION, color = as.factor(clusterf$cluster)))+
  geom_point()+
  geom_point(data = as.data.frame(clusterf2$centers), aes(x=PEI4, y = ID_EMIGRACION), color = "black", size=4, shape=17)+
  labs(title = "Edad vs Año Número del emigrante")+
  theme_minimal()


graficaf2

```

```{r}

#Filtramos por omitiendo los años de 9999
dataf3 <- subset(data, PEI5 < 2025)

dataf3

# Ejecutamos Kmeans con el nuevo dataset
clusterf3 <- kmeans(dataf3, centers=4)

clusterf3

#Grafica
graficaf3 <- ggplot(dataf3, aes(x = DEPARTAMENTO, y = PEI5, color = as.factor(clusterf3$cluster)))+
  geom_point()+
  geom_point(data = as.data.frame(clusterf3$centers), aes(x=DEPARTAMENTO, y = PEI5), color = "black", size=4, shape=17)+
  labs(title = "Deparamento vs Año Emigración")+
  theme_minimal()


graficaf3

```